import type { ShopProduct } from './catalog-shared';
export { money, categories, brands } from './catalog-shared';
export type { ShopProduct, ShopVariant } from './catalog-shared';
const phone = (
  id: string,
  title: string,
  brand: string,
  price: number,
  old: number,
  color: string,
  hex: string,
  image: string,
  badge: string,
  description: string,
): ShopProduct => ({
  id,
  slug: id,
  title,
  brand,
  category: 'Smartphones',
  subtitle: 'Powerful by nature. Beautiful by design.',
  description,
  warranty:
    '1 year manufacturer warranty. 6 months warranty on included accessories. Manufacturer terms apply.',
  specifications: {
    Display: '6.7-inch OLED · 120Hz',
    Camera: 'Advanced triple camera system',
    Battery: 'All-day battery · Fast charging',
    Connectivity: '5G · Wi-Fi 6 · Bluetooth',
    OS: brand === 'Apple' ? 'iOS' : 'Android',
  },
  badge,
  featured: true,
  status: 'ACTIVE',
  images: [image, image],
  rating: 4.8,
  reviewCount: 124,
  demo: true,
  variants: [
    {
      id: `${id}-256`,
      sku: `${id}-256`,
      color,
      colorHex: hex,
      ram: '8 GB',
      storage: '256 GB',
      price: price * 100,
      originalPrice: old * 100,
      stock: 24,
      reserved: 0,
    },
    {
      id: `${id}-512`,
      sku: `${id}-512`,
      color,
      colorHex: hex,
      ram: '8 GB',
      storage: '512 GB',
      price: (price + 10000) * 100,
      originalPrice: (old + 10000) * 100,
      stock: 8,
      reserved: 0,
    },
    {
      id: `${id}-black`,
      sku: `${id}-black`,
      color: 'Midnight',
      colorHex: '#282b30',
      ram: '12 GB',
      storage: '256 GB',
      price: (price + 2000) * 100,
      originalPrice: (old + 2000) * 100,
      stock: 4,
      reserved: 0,
    },
  ],
});
export const demoProducts: ShopProduct[] = [
  phone(
    'iphone-16-pro',
    'iPhone 16 Pro',
    'Apple',
    112900,
    119900,
    'Desert Titanium',
    '#c8ad96',
    '/products/iphone-pro.webp',
    'BEST SELLER',
    'A remarkably powerful pro camera system. A stunning titanium design. Built for your next big idea.',
  ),
  phone(
    'galaxy-s25-ultra',
    'Galaxy S25 Ultra',
    'Samsung',
    119999,
    129999,
    'Titanium Silver',
    '#b3bec4',
    '/products/galaxy.webp',
    'NEW ARRIVAL',
    'Meet your everyday creative companion. A brilliant display, precision cameras, and effortless performance.',
  ),
  phone(
    'pixel-9-pro',
    'Pixel 9 Pro',
    'Google',
    99999,
    109999,
    'Porcelain',
    '#d8d5c8',
    '/products/pixel.webp',
    'EXCLUSIVE',
    'A little more magic in every moment. Discover intelligent photography and a beautifully simple experience.',
  ),
  phone(
    'oneplus-13',
    'OnePlus 13',
    'OnePlus',
    69999,
    74999,
    'Arctic Dawn',
    '#d4e4ed',
    '/products/oneplus.webp',
    'GREAT VALUE',
    'Smooth performance. Exceptional battery life. A flagship experience made for life at full speed.',
  ),
  phone(
    'iphone-16',
    'iPhone 16',
    'Apple',
    74900,
    79900,
    'Ultramarine',
    '#7888be',
    '/products/iphone-blue.webp',
    'POPULAR',
    'Colorful. Capable. Ready for anything. Capture everyday moments in extraordinary detail.',
  ),
  phone(
    'galaxy-a56',
    'Galaxy A56 5G',
    'Samsung',
    38999,
    41999,
    'Awesome Graphite',
    '#4d6260',
    '/products/galaxy-green.webp',
    'OFFER',
    'Everything you love, thoughtfully brought together. A vivid display and dependable performance.',
  ),
  {
    id: 'airpods-pro',
    slug: 'airpods-pro',
    title: 'AirPods Pro 2',
    brand: 'Apple',
    category: 'Audio',
    subtitle: 'Sound that surrounds you.',
    description:
      'Immersive sound, active noise cancellation, and an effortless wireless experience.',
    warranty: '1 year manufacturer warranty',
    specifications: {
      Connectivity: 'Bluetooth',
      Features: 'Active noise cancellation',
      Battery: 'Up to 30 hours with case',
    },
    badge: 'TRENDING',
    featured: true,
    status: 'ACTIVE',
    images: ['/products/earbuds.webp'],
    variants: [
      {
        id: 'airpods-pro-white',
        sku: 'AIRPODS-WHITE',
        color: 'White',
        colorHex: '#f0f0ed',
        ram: 'N/A',
        storage: 'N/A',
        price: 2290000,
        originalPrice: 2490000,
        stock: 30,
        reserved: 0,
      },
    ],
    rating: 4.9,
    reviewCount: 86,
    demo: true,
  },
  {
    id: 'watch-series-10',
    slug: 'watch-series-10',
    title: 'Watch Series 10',
    brand: 'Apple',
    category: 'Wearables',
    subtitle: 'A healthier day starts here.',
    description:
      'A beautifully bright display and thoughtful everyday health and fitness features.',
    warranty: '1 year manufacturer warranty',
    specifications: {
      Display: 'Always-on OLED',
      Connectivity: 'Bluetooth · Wi-Fi',
      Features: 'Fitness and activity tracking',
    },
    badge: 'NEW',
    featured: true,
    status: 'ACTIVE',
    images: ['/products/watch.webp'],
    variants: [
      {
        id: 'watch-black',
        sku: 'WATCH-BLACK',
        color: 'Jet Black',
        colorHex: '#252525',
        ram: 'N/A',
        storage: 'N/A',
        price: 4290000,
        originalPrice: 4690000,
        stock: 10,
        reserved: 0,
      },
    ],
    rating: 4.7,
    reviewCount: 52,
    demo: true,
  },
  {
    id: 'fast-charger',
    slug: 'fast-charger',
    title: '65W GaN Charger',
    brand: 'Anker',
    category: 'Chargers',
    subtitle: 'Small size. Serious power.',
    description: 'Compact multi-device charging with intelligent power distribution.',
    warranty: '18 month manufacturer warranty',
    specifications: { Power: '65W', Ports: '2 USB-C · 1 USB-A', Technology: 'GaN' },
    badge: 'ESSENTIAL',
    featured: true,
    status: 'ACTIVE',
    images: ['/products/charger.webp'],
    variants: [
      {
        id: 'charger-black',
        sku: 'GAN-65W',
        color: 'Black',
        colorHex: '#262830',
        ram: 'N/A',
        storage: 'N/A',
        price: 349900,
        originalPrice: 499900,
        stock: 35,
        reserved: 0,
      },
    ],
    rating: 4.6,
    reviewCount: 39,
    demo: true,
  },
  {
    id: 'silicone-case',
    slug: 'silicone-case',
    title: 'Magnetic Silicone Case',
    brand: 'Spigen',
    category: 'Cases',
    subtitle: 'Protection with personality.',
    description: 'Soft-touch finish, magnetic alignment, and thoughtful everyday protection.',
    warranty: '6 month manufacturer warranty',
    specifications: {
      Material: 'Silicone',
      Compatibility: 'iPhone 16 Pro',
      Features: 'Magnetic charging compatible',
    },
    badge: 'OFFER',
    featured: true,
    status: 'ACTIVE',
    images: ['/products/case.webp'],
    variants: [
      {
        id: 'case-blue',
        sku: 'CASE-BLUE',
        color: 'Slate Blue',
        colorHex: '#6c8399',
        ram: 'N/A',
        storage: 'N/A',
        price: 199900,
        originalPrice: 299900,
        stock: 40,
        reserved: 0,
      },
    ],
    rating: 4.5,
    reviewCount: 22,
    demo: true,
  },
];
